[feat] shell read and wrtie 구현 및 테스트 코드
kwakmandu/Aut_ut_hul pull request #11
Opened 2024-07-15 23:45 UTC by kwakmandu

## Description
- shell.py, test_shell.py -  read, write 기능 구현

## Changes
- Shell() 객체 생성시 속성에 ssd 객체 부여
```py
self.ssd: StorageDeviceInterface = VirtualSSD()
```

- 추후 ssd가 여러개라면 ssd setter 메서드 생성 필요

## For reviewers
- 변경할 사항이 있으면 편하게 말씀 부탁드립니다~

2024-07-15 23:52 UTC, dongheelim approved these changes
코드 확인했습니다. 수고많으셨씁니다!

2024-07-15 23:55 UTC, Wontae-jeong requested changes

2024-07-15 23:55 UTC, Wontae-jeong commented on shell/shell.py
> +                self.write(int(inputs[2]), inputs[3])
int("0xABCD") -> 저희가 의도한 결과가 안나오지 않을까요?

2024-07-15 23:58 UTC, Wontae-jeong approved these changes

2024-07-15 23:58 UTC, Wontae-jeong commented on shell/shell.py
> +                self.write(int(inputs[2]), inputs[3])
`inputs[2]`가 numeric value인지 확인하는 로직이 추후 필요한것 같습니다

2024-07-15 23:58 UTC, Wontae-jeong commented on shell/shell.py
> +                self.write(int(inputs[2]), inputs[3])
예시) `ssd W hello world`

2024-07-16 00:06 UTC, kwakmandu commented on shell/shell.py
> +                self.write(int(inputs[2]), inputs[3])
아 맞네욥!! 저희 validate도 구현을 해야겠네욥

2024-07-16 00:31 UTC, merged